spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      #mongodb+srv://sead-afk:w2XEsXn2Q_aq2Db@cluster0.mdzkpw1.mongodb.net/travelDB?retryWrites=true&w=majority

logging:
  level:
    org.springframework:
      security: DEBUG
      data.mongodb.core.MongoTemplate: INFO

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 3600000 # Token expiration in milliseconds (1 hour)


